<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-18 at 06:45:28.
 */
class AutoLoaderTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var AutoLoader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AutoLoader;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers AutoLoader::registerDirectory
     * @todo   Implement testRegisterDirectory().
     */
    public function testRegisterDirectory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AutoLoader::registerClass
     * @todo   Implement testRegisterClass().
     */
    public function testRegisterClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AutoLoader::loadClass
     * @todo   Implement testLoadClass().
     */
    public function testLoadClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
