<?php

namespace lib\core;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-23 at 14:51:52.
 */
class HttpResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var HttpResponse
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HttpResponse;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

}
